Algoritmo "Matrizes 1"
// Disciplina   : Lógica de Programação
// Professor   : Renato Corvello
// Descrição   : Exercício Matriz 1
// Autor(a)    : Nateus Kaufmann
// Data atual  : 22/08/2021
Var
i: inteiro
j: inteiro
tabela : vetor [1..7,1..8] de inteiro


Inicio

para i <- 1 até 7 faça
     para j <- 1 até 8 faça
          tabela [i, j ] <- i+j
     fimpara
fimpara



Fimalgoritmo